In [1]:
from sklearn.neighbors import KNeighborsClassifier

In [2]:
from sklearn.datasets import load_iris

In [3]:
import numpy as np

In [4]:
knn=KNeighborsClassifier(n_neighbors=1)

In [5]:
iris=load_iris()

In [6]:
X=iris.data
y=iris.target

In [7]:
print(knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


In [8]:
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [9]:
knn.predict([3,4,5,6])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([2])

In [10]:
x_new=np.array([[3,4,5,2],[5,4,3,2]])

In [11]:
knn.predict(x_new)

array([2, 1])

In [12]:
#model tuning
knn2=KNeighborsClassifier(n_neighbors=5)

In [13]:
knn2.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [14]:
knn2.predict(x_new)

array([1, 1])

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
logreg=LogisticRegression()

In [17]:
logreg.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [18]:
logreg.predict(x_new)

array([2, 0])

In [19]:
y_predict=logreg.predict(X)

In [20]:
len(y_predict)

150

In [21]:
y_predict.shape

(150,)

In [22]:
#classification accuracy
from sklearn import metrics

In [23]:
#logistic regression accuracy
print(metrics.accuracy_score(y,y_predict))

0.96


In [24]:
y_p2=knn.predict(X)
y_p3=knn2.predict(X)

In [25]:
#knn=1
print(metrics.accuracy_score(y,y_p2))

1.0


In [26]:
#knn=5
print(metrics.accuracy_score(y,y_p3))

0.9666666666666667
